name: Notify on Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request with PR info
        run: |
          curl -X POST https://hooks.slack.com/services/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 \
          -H "Content-Type: application/json" \
          -d '{
            "title": "${{ github.event.pull_request.title }}",
            "url": "${{ github.event.pull_request.html_url }}",
            "user": "${{ github.event.pull_request.user.login }}",
            "action": "${{ github.event.action }}"
          }'
